CREATE DATABASE IF NOT EXISTS spacesync;
CREATE TABLE IF NOT EXISTS triggers(
  "id" SERIAL PRIMARY KEY NOT NULL,
  "name" varchar(255) NOT NULL,
  "scheduling_date" TIMESTAMP WITH TIME ZONE NULL,
  "delay" INTEGER NOT NULL,
  "copyright" TEXT NOT NULL,
  "status" varchar(255) NOT NULL DEFAULT 'pending',
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NULL
);
CREATE TABLE IF NOT EXISTS images(
  "id" SERIAL PRIMARY KEY NOT NULL,
  "url" TEXT NOT NULL,
  "trigger_id" INTEGER REFERENCES triggers(id) ON DELETE CASCADE,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NULL
);
CREATE TABLE IF NOT EXISTS groups(
  "id" SERIAL PRIMARY KEY NOT NULL,
  "serialized_identifier" varchar(255) NOT NULL,
  -- "name" varchar(255) NOT NULL,
  "trigger_id" INTEGER REFERENCES triggers(id) ON DELETE CASCADE,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NULL
)