export const VenomStatus = {
	isLogged: 'Você já está conectado',
	notLogged: 'Você ainda não está conectado',
	browserClose: 'O browser foi fechado',
	qrReadSuccess: 'QR Code lido',
	qrReadFail: 'Falha ao ler QR Code',
	autocloseCalled: 'O browser foi fechado',
	desconnectedMobile: 'Desconectado do celular',
	serverClose: 'O servidor foi fechado',
	deleteToken: 'Token excluído',
	chatsAvailable: 'Chats disponíveis',
	deviceNotConnected: 'Dispositivo não conectado',
	noOpenBrowser: 'Nenhum browser aberto',
	serverWssNotConnected: 'Servidor WSS não conectado',
	initBrowser: 'Iniciando browser',
	openBrowser: 'Browser iniciado',
	connectBrowserWs: 'Conectando browser WSS',
	initWhatsapp: 'Iniciando recursos do whatsapp',
	erroPageWhatsapp: 'Erro ao iniciar recursos do whatsapp',
	successPageWhatsapp: 'Recursos do whatsapp iniciados',
	waitForLogin: 'Aguardando a verificação de login',
	waitChat: 'Esperando Chat',
	successChat: 'Chat iniciado',
	offline: 'Sessão offline',
	online: 'Sessão online',
};
