export const VenomStatus = {
	isLogged: 'Você já está conectado',
	notLogged: 'Você ainda não está conectado, conecte-se',
	browserClose: 'Ops! A instância foi fechada',
	qrReadSuccess: 'O QRCode foi lido com sucesso!',
	qrReadFail: 'Ops! Houve uma falha ao ler QR Code',
	autocloseCalled: 'Ops! A instância foi fechada',
	desconnectedMobile: 'Ops! parece que seu dispositivo foi desconectado',
	serverClose: 'Ops! O servidor foi desconectado',
	deleteToken: 'O Token da sua instância foi removido',
	chatsAvailable: 'Chats disponíveis',
	deviceNotConnected: 'Ops! para o seu dispositivo não está conectado',
	noOpenBrowser: 'Ops! a instância ainda não foi iniciada',
	serverWssNotConnected: 'Ops! o Servidor WSS não foi conectado',
	initBrowser: 'Iniciando uma nova instância',
	openBrowser: 'Sua instância foi iniciada',
	connectBrowserWs: 'Conectando ao Servidor WSS',
	initWhatsapp: 'Iniciando recursos do whatsapp',
	erroPageWhatsapp: 'Erro ao iniciar recursos do whatsapp',
	successPageWhatsapp: 'Recursos do whatsapp iniciados',
	waitForLogin: 'Aguardando a verificação de login',
	waitChat: 'Esperando Chat',
	successChat: 'Chat iniciado',
	offline: 'Sessão offline',
	online: 'Sessão online',
};
